// 节点聚合器：通过 anonymous import 触发各节点的 init() 注册
// 主程序 import 本包即可拉起所有内置节点
// 新增节点 = 新增一个子包 + 在这里加一行 import

package nodes

import (
	_ "OpsEngine/internal/nodes/arith"
	_ "OpsEngine/internal/nodes/assemble_end"
	_ "OpsEngine/internal/nodes/assemble_param"
	_ "OpsEngine/internal/nodes/assemble_start"
	_ "OpsEngine/internal/nodes/branch_node"
	_ "OpsEngine/internal/nodes/break_node"
	_ "OpsEngine/internal/nodes/compare"
	_ "OpsEngine/internal/nodes/docker_build"
	_ "OpsEngine/internal/nodes/docker_connect"
	_ "OpsEngine/internal/nodes/docker_exec"
	_ "OpsEngine/internal/nodes/docker_filter"
	_ "OpsEngine/internal/nodes/docker_logs"
	_ "OpsEngine/internal/nodes/docker_ps"
	_ "OpsEngine/internal/nodes/docker_pull"
	_ "OpsEngine/internal/nodes/docker_push"
	_ "OpsEngine/internal/nodes/docker_restart"
	_ "OpsEngine/internal/nodes/docker_rm"
	_ "OpsEngine/internal/nodes/docker_run"
	_ "OpsEngine/internal/nodes/docker_stop"
	_ "OpsEngine/internal/nodes/env_connect_docker"
	_ "OpsEngine/internal/nodes/env_connect_jenkins"
	_ "OpsEngine/internal/nodes/env_connect_k8s"
	_ "OpsEngine/internal/nodes/env_connect_ssh"
	_ "OpsEngine/internal/nodes/env_probe_docker_containers"
	_ "OpsEngine/internal/nodes/env_probe_jenkins_jobs"
	_ "OpsEngine/internal/nodes/env_probe_k8s_pods"
	_ "OpsEngine/internal/nodes/env_probe_ssh_find_files"
	_ "OpsEngine/internal/nodes/env_probe_ssh_list_dir"
	_ "OpsEngine/internal/nodes/for_loop"
	_ "OpsEngine/internal/nodes/k8s_connect"
	_ "OpsEngine/internal/nodes/linux_download_file"
	_ "OpsEngine/internal/nodes/linux_exec_command"
	_ "OpsEngine/internal/nodes/linux_exec_script"
	_ "OpsEngine/internal/nodes/linux_file_append"
	_ "OpsEngine/internal/nodes/linux_file_replace"
	_ "OpsEngine/internal/nodes/linux_file_write"
	_ "OpsEngine/internal/nodes/linux_find_file"
	_ "OpsEngine/internal/nodes/linux_open_file"
	_ "OpsEngine/internal/nodes/logic"
	_ "OpsEngine/internal/nodes/parallel"
	_ "OpsEngine/internal/nodes/print"
	_ "OpsEngine/internal/nodes/return_set"
	_ "OpsEngine/internal/nodes/ssh_with_linux"
	_ "OpsEngine/internal/nodes/system_over"
	_ "OpsEngine/internal/nodes/system_ready"
	_ "OpsEngine/internal/nodes/system_update"
	_ "OpsEngine/internal/nodes/thread"
	_ "OpsEngine/internal/nodes/to_string"
	_ "OpsEngine/internal/nodes/varget"
	_ "OpsEngine/internal/nodes/varset"
	_ "OpsEngine/internal/nodes/while_loop"
)
